;/////////////////////////////////////////////////////////////////////////////
;///	   	3Pl Evil Ending by Powerkartoffel                   ///
;///////////////////////////////////////////////////////////////////////////// 

;-----------------------------------------------------------------




AIData
	UseLowLODTrees 		= No ;;.;;
END

WaterTransparency
	ReflectionPlaneZ 	= 304.0;
	ReflectionOn 		= Yes
End

Weather

	HardwareFogColor 	= R:120 G:125 B:140
	HardwareFogEnable 	= Yes
	HardwareFogStart 	= 750
	HardwareFogEnd 		= 4700	

    SnowEnabled = Yes               ; enable/disable snow on the map.
    IsSnowing = Yes               ; is it snowing today?
    SnowTexture = exsnowflake2.tga
    SnowBoxHeight = 5000             ; height from which snow falls
    SnowSpacing = 100             ; snow spacing -- less means more
    NumberTiles = 2

    SnowAmplitude = 3              ; amount of side-to-side movement. 
    SnowFrequencyScaleX = 0.02        ; speed of side-to-side wave movement.
    SnowFrequencyScaleY = 0.02         ; speed of side-to-side wave movement. 

    SnowPointSize = 3               ; scale the size of snow particles.
    SnowMinPointSize = 5           ; min point size
    SnowMaxPointSize = 15           ; max point size

    SnowPointSprites = No           ; set to "no" for point-sprite emulation.
    SnowQuadSize = 2.5               ; scale the size of snow particles when using point-sprite emulation.

    SnowSpeed = 120.0               ; speed at which snow falls
    SnowXYSpeed = X:-55 Y:0
End

FXParticleSystem PK_Teleport1
  System
    Priority = VERY_LOW_OR_ABOVE
    Shader = ALPHA
    ParticleName = EXsmokeplume.tga

    Lifetime = 90 110
    SortLevel = 1
    Size = 3 6
    BurstDelay = 10 10
    BurstCount = 4 4
  End

  Color = DefaultColor
    Color1 = R:255 G:255 B:255 0
    Color2 = R:240 G:240 B:255 45
  End

  Alpha = DefaultAlpha
    Alpha1 = 0.5 0.6 0
    Alpha2 = 0 0 90
  End

  Update = DefaultUpdate
    SizeRate = 1.5 2.5
    SizeRateDamping = 0.97 0.97
    AngleZ = -0.5 0.5
    AngularRateZ = -0.1 0.1
    AngularDamping = 0.9 0.9
    AngularDampingXY = 1 1
  End

  Physics = DefaultPhysics
    Gravity = 0.015
    VelocityDamping = 0.8 0.85
    DriftVelocity = X:0 Y:0 Z:0
  End

  EmissionVelocity = OutwardEmissionVelocity
  End

  EmissionVolume = CylinderEmissionVolume
    Radius = 40
    Length = 3
  End

  Draw = DefaultDraw
  End
End

FXParticleSystem PK_Teleport2
  System
    Priority = VERY_LOW_OR_ABOVE
    Shader = ALPHA
    ParticleName = EXsmokeplume.tga

    Lifetime = 90 110
    SortLevel = 1
    Size = 3 6
    BurstDelay = 10 10
    BurstCount = 4 4
  End

  Color = DefaultColor
    Color1 = R:150 G:110 B:90 0
    Color2 = R:120 G:80 B:60 45
  End

  Alpha = DefaultAlpha
    Alpha1 = 0.5 0.6 0
    Alpha2 = 0 0 90
  End

  Update = DefaultUpdate
    SizeRate = 1.5 2.5
    SizeRateDamping = 0.97 0.97
    AngleZ = -0.5 0.5
    AngularRateZ = -0.1 0.1
    AngularDamping = 0.9 0.9
    AngularDampingXY = 1 1
  End

  Physics = DefaultPhysics
    Gravity = 0.015
    VelocityDamping = 0.8 0.85
    DriftVelocity = X:0 Y:0 Z:0
  End

  EmissionVelocity = OutwardEmissionVelocity
  End

  EmissionVolume = CylinderEmissionVolume
    Radius = 40
    Length = 3
  End

  Draw = DefaultDraw
  End
End

ChildObject IsengardBuildingFoundation IsengardBuildingFoundation

	Draw = W3DScriptedModelDraw ModuleTag_01
		DefaultModelConditionState
			Model = OBBFoundationX
			ParticleSysBone = None PK_Teleport1
		End
    End

	Draw = W3DFloorDraw ModuleTag_Draw
		ModelName = HBFoundationX
	End

	SelectPortrait = LWPErebor

	; ***DESIGN parameters ***
	DisplayName        	= OBJECT:WildMineShaft
	Description 	    = OBJECT:UndermineMineShaft
	EditorSorting       = STRUCTURE
	VisionRange         = 160.0          ; Shroud clearing distance
	ShroudClearingRange = GONDOR_WORKSHOP_SHROUD_CLEAR
 	CommandSet			= HobbitWorkPitCommandSet
 
  ArmorSet
    Conditions        = None
    Armor             = InvulnerableArmor ;;=;; StructureArmor ; ;
  End

	; *** AUDIO Parameters ***

	VoiceSelect				= WildDefiledMineSelect

	;UnitSpecificSounds
	;End


	; *** ENGINEERING Parameters ***

	RadarPriority       = STRUCTURE
	KindOf              = PRELOAD STRUCTURE SELECTABLE IMMOBILE SCORE GARRISON GARRISONABLE_UNTIL_DESTROYED MADE_OF_STONE CHUNK_VENDOR ALWAYS_SHOW_HOUSE_COLOR LINKED_TO_FLAG NOT_AUTOACQUIRABLE
	
	Behavior       = EvacuateDamage ModuleTag_evacuateDamage
		DamageToPanicThreshold = 0% 
		TrackingTimeSpan = 100
	End
	Behavior = AttributeModifierAuraUpdate ModuleTag_MineshaftContainedBonus ;;,;;
		StartsActive    = Yes
		BonusName        = MineshaftContainedBonus_202aa
		RefreshDelay    = 100
		AffectContainedOnly = Yes
		AllowSelf = Yes
	End	
	
	Behavior = HordeGarrisonContain ModuleTag_hordeGarrison
		ObjectStatusOfContained	= UNSELECTABLE ENCLOSED 
		ContainMax              = 10
		DamagePercentToUnits    = 0%
		PassengerFilter			= TRANSPORTSHIP_PASSENGER_OBJECTFILTER
		AllowEnemiesInside      = No
		AllowAlliesInside      	= Yes
		AllowNeutralInside      = Yes	; Cause this structure is normally neutral.
;		DoorOpenTime 			= 1
		NumberOfExitPaths       = 1		; Defaults to 1.  Set 0 to not use ExitStart/ExitEnd, set higher than 1 to use ExitStart01-nn/ExitEnd01-nn
		PassengerBonePrefix     = PassengerBone:SAIL_BONE KindOf:INFANTRY
		EntryPosition			= X:4537 Y:1320 Z:-60.0
		EntryOffset				= X:0.0 Y:0.0 Z:0.0
		ExitOffset				= X:4359 Y:1322 Z:-60.0
		ExitDelay				= 0.1
		EnterSound				= GarrisonEnter
		KillPassengersOnDeath	= No
		ShowPips				= No
	End
	Behavior = GrantUpgradeCreate ModuleTag_GrantUpgrade
		UpgradeToGrant = Upgrade_ObjectLevel1
	End
	Behavior = ObjectCreationUpgrade ModuleTag_SpawnObject
		TriggeredBy 	= Upgrade_ObjectLevel1
		ThingToSpawn	= InstantShroudRevealer_09v3
	End	
	GeometryContactPoint = X:20.0	Y:-20.0	Z:0			Repair

	Geometry              = CYLINDER
	GeometryMajorRadius   = 100.0
	GeometryMinorRadius   = 100.0
	GeometryHeight        = 10.0
	GeometryIsSmall       = Yes
	Shadow                = SHADOW_VOLUME
	BuildCompletion     = PLACED_BY_PLAYER
	
End

ChildObject ElvenBuildingFoundation ElvenBuildingFoundation

	Draw = W3DScriptedModelDraw ModuleTag_01
		DefaultModelConditionState
			Model = OBBFoundationX
			ParticleSysBone = None PK_Teleport1
		End
    End

	Draw = W3DFloorDraw ModuleTag_Draw
		ModelName = HBFoundationX
	End
	
	SelectPortrait = LWPErebor

	; ***DESIGN parameters ***
	DisplayName        	= OBJECT:WildMineShaft
	Description 	    = OBJECT:UndermineMineShaft
	EditorSorting       = STRUCTURE
	VisionRange         = 160.0          ; Shroud clearing distance
	ShroudClearingRange = GONDOR_WORKSHOP_SHROUD_CLEAR
 	CommandSet			= HobbitWorkPitCommandSet
 
  ArmorSet
    Conditions        = None
    Armor             = InvulnerableArmor ;;=;; StructureArmor ; ;
  End

	; *** AUDIO Parameters ***

	VoiceSelect				= WildDefiledMineSelect

	;UnitSpecificSounds
	;End


	; *** ENGINEERING Parameters ***

	RadarPriority       = STRUCTURE
	KindOf              = PRELOAD STRUCTURE SELECTABLE IMMOBILE SCORE GARRISON GARRISONABLE_UNTIL_DESTROYED MADE_OF_STONE CHUNK_VENDOR ALWAYS_SHOW_HOUSE_COLOR LINKED_TO_FLAG NOT_AUTOACQUIRABLE
	
	Behavior       = EvacuateDamage ModuleTag_evacuateDamage
		DamageToPanicThreshold = 0% 
		TrackingTimeSpan = 100
	End
	
	
	Behavior = AttributeModifierAuraUpdate ModuleTag_MineshaftContainedBonus ;;,;;
		StartsActive    = Yes
		BonusName        = MineshaftContainedBonus_202aa
		RefreshDelay    = 100
		AffectContainedOnly = Yes
		AllowSelf = Yes
	End	
	
	Behavior = HordeGarrisonContain ModuleTag_hordeGarrison
		ObjectStatusOfContained	= UNSELECTABLE ENCLOSED 
		ContainMax              = 10
		DamagePercentToUnits    = 0%
		PassengerFilter			= TRANSPORTSHIP_PASSENGER_OBJECTFILTER
		AllowEnemiesInside      = No
		AllowAlliesInside      	= Yes
		AllowNeutralInside      = Yes	; Cause this structure is normally neutral.
;		DoorOpenTime 			= 1
		NumberOfExitPaths       = 1		; Defaults to 1.  Set 0 to not use ExitStart/ExitEnd, set higher than 1 to use ExitStart01-nn/ExitEnd01-nn
		PassengerBonePrefix     = PassengerBone:SAIL_BONE KindOf:INFANTRY
		EntryPosition			= X:4354 Y:1121 Z:-60.0
		EntryOffset				= X:0.0 Y:0.0 Z:0.0
		ExitOffset				= X:4191 Y:1069 Z:-60.0
		ExitDelay				= 0.1
		EnterSound				= GarrisonEnter
		KillPassengersOnDeath	= No
		ShowPips				= No
	End
	Behavior = GrantUpgradeCreate ModuleTag_GrantUpgrade
		UpgradeToGrant = Upgrade_ObjectLevel1
	End
	Behavior = ObjectCreationUpgrade ModuleTag_SpawnObject
		TriggeredBy 	= Upgrade_ObjectLevel1
		ThingToSpawn	= InstantShroudRevealer_09v3
	End	
	GeometryContactPoint = X:20.0	Y:-20.0	Z:0			Repair

	Geometry              = CYLINDER
	GeometryMajorRadius   = 100.0
	GeometryMinorRadius   = 100.0
	GeometryHeight        = 10.0
	GeometryIsSmall       = Yes
	Shadow                = SHADOW_VOLUME
	BuildCompletion     = PLACED_BY_PLAYER
	
End

ChildObject GondorBuildingFoundation_Independant GondorBuildingFoundation_Independant

	Draw = W3DScriptedModelDraw ModuleTag_01
		DefaultModelConditionState
			Model = OBBFoundationX
			ParticleSysBone = None PK_Teleport2
		End
    End

	Draw = W3DFloorDraw ModuleTag_Draw
		ModelName = HBFoundationX
	End
	
	SelectPortrait = LWPErebor

	; ***DESIGN parameters ***
	DisplayName        	= OBJECT:WildMineShaft
	Description 	    = OBJECT:UndermineMineShaft
	EditorSorting       = STRUCTURE
	VisionRange         = 160.0          ; Shroud clearing distance
	ShroudClearingRange = GONDOR_WORKSHOP_SHROUD_CLEAR
 	CommandSet			= HobbitWorkPitCommandSet
 
  ArmorSet
    Conditions        = None
    Armor             = InvulnerableArmor ;;=;; StructureArmor ; ;
  End

	; *** AUDIO Parameters ***

	VoiceSelect				= WildDefiledMineSelect

	;UnitSpecificSounds
	;End


	; *** ENGINEERING Parameters ***

	RadarPriority       = STRUCTURE
	KindOf              = PRELOAD STRUCTURE SELECTABLE IMMOBILE SCORE GARRISON GARRISONABLE_UNTIL_DESTROYED MADE_OF_STONE CHUNK_VENDOR ALWAYS_SHOW_HOUSE_COLOR LINKED_TO_FLAG NOT_AUTOACQUIRABLE
	
	Behavior       = EvacuateDamage ModuleTag_evacuateDamage
		DamageToPanicThreshold = 0% 
		TrackingTimeSpan = 100
	End
	Behavior = AttributeModifierAuraUpdate ModuleTag_MineshaftContainedBonus ;;,;;
		StartsActive    = Yes
		BonusName        = MineshaftContainedBonus_202aa
		RefreshDelay    = 100
		AffectContainedOnly = Yes
		AllowSelf = Yes
	End	
	
	Behavior = HordeGarrisonContain ModuleTag_hordeGarrison
		ObjectStatusOfContained	= UNSELECTABLE ENCLOSED 
		ContainMax              = 10
		DamagePercentToUnits    = 0%
		PassengerFilter			= TRANSPORTSHIP_PASSENGER_OBJECTFILTER
		AllowEnemiesInside      = No
		AllowAlliesInside      	= Yes
		AllowNeutralInside      = Yes	; Cause this structure is normally neutral.
;		DoorOpenTime 			= 1
		NumberOfExitPaths       = 1		; Defaults to 1.  Set 0 to not use ExitStart/ExitEnd, set higher than 1 to use ExitStart01-nn/ExitEnd01-nn
		PassengerBonePrefix     = PassengerBone:SAIL_BONE KindOf:INFANTRY
		EntryPosition			= X:4537 Y:1320 Z:60.0
		EntryOffset				= X:0.0 Y:0.0 Z:0.0
		ExitOffset				= X:4340 Y:1364 Z:60.0
		ExitDelay				= 0.1
		EnterSound				= GarrisonEnter
		KillPassengersOnDeath	= No
		ShowPips				= No
	End
	Behavior = GrantUpgradeCreate ModuleTag_GrantUpgrade
		UpgradeToGrant = Upgrade_ObjectLevel1
	End
	Behavior = ObjectCreationUpgrade ModuleTag_SpawnObject
		TriggeredBy 	= Upgrade_ObjectLevel1
		ThingToSpawn	= InstantShroudRevealer_09v3
	End	
	GeometryContactPoint = X:20.0	Y:-20.0	Z:0			Repair

	Geometry              = CYLINDER
	GeometryMajorRadius   = 100.0
	GeometryMinorRadius   = 100.0
	GeometryHeight        = 10.0
	GeometryIsSmall       = Yes
	Shadow                = SHADOW_VOLUME
	BuildCompletion     = PLACED_BY_PLAYER
	
End


ChildObject GondorBuildingFoundation GondorBuildingFoundation

	Draw = W3DScriptedModelDraw ModuleTag_01
		DefaultModelConditionState
			Model = OBBFoundationX
			ParticleSysBone = None PK_Teleport2
		End
    End

	Draw = W3DFloorDraw ModuleTag_Draw
		ModelName = HBFoundationX
	End
	
	SelectPortrait = LWPErebor

	; ***DESIGN parameters ***
	DisplayName        	= OBJECT:WildMineShaft
	Description 	    = OBJECT:UndermineMineShaft
	EditorSorting       = STRUCTURE
	VisionRange         = 160.0          ; Shroud clearing distance
	ShroudClearingRange = GONDOR_WORKSHOP_SHROUD_CLEAR
 	CommandSet			= HobbitWorkPitCommandSet
 
  ArmorSet
    Conditions        = None
    Armor             = InvulnerableArmor ;;=;; StructureArmor ; ;
  End

	; *** AUDIO Parameters ***

	VoiceSelect				= WildDefiledMineSelect

	;UnitSpecificSounds
	;End


	; *** ENGINEERING Parameters ***

	RadarPriority       = STRUCTURE
	KindOf              = PRELOAD STRUCTURE SELECTABLE IMMOBILE SCORE GARRISON GARRISONABLE_UNTIL_DESTROYED MADE_OF_STONE CHUNK_VENDOR ALWAYS_SHOW_HOUSE_COLOR LINKED_TO_FLAG NOT_AUTOACQUIRABLE
	
	Behavior       = EvacuateDamage ModuleTag_evacuateDamage
		DamageToPanicThreshold = 0% 
		TrackingTimeSpan = 100
	End
	Behavior = AttributeModifierAuraUpdate ModuleTag_MineshaftContainedBonus ;;,;;
		StartsActive    = Yes
		BonusName        = MineshaftContainedBonus_202aa
		RefreshDelay    = 100
		AffectContainedOnly = Yes
		AllowSelf = Yes
	End	
	
	Behavior = HordeGarrisonContain ModuleTag_hordeGarrison
		ObjectStatusOfContained	= UNSELECTABLE ENCLOSED 
		ContainMax              = 10
		DamagePercentToUnits    = 0%
		PassengerFilter			= TRANSPORTSHIP_PASSENGER_OBJECTFILTER
		AllowEnemiesInside      = No
		AllowAlliesInside      	= Yes
		AllowNeutralInside      = Yes	; Cause this structure is normally neutral.
;		DoorOpenTime 			= 1
		NumberOfExitPaths       = 1		; Defaults to 1.  Set 0 to not use ExitStart/ExitEnd, set higher than 1 to use ExitStart01-nn/ExitEnd01-nn
		PassengerBonePrefix     = PassengerBone:SAIL_BONE KindOf:INFANTRY
		EntryPosition			= X:4354 Y:1121 Z:60.0
		EntryOffset				= X:0.0 Y:0.0 Z:0.0
		ExitOffset				= X:4153 Y:1222 Z:60.0
		ExitDelay				= 0.1
		EnterSound				= GarrisonEnter
		KillPassengersOnDeath	= No
		ShowPips				= No
	End
	
	Behavior = GrantUpgradeCreate ModuleTag_GrantUpgrade
		UpgradeToGrant = Upgrade_ObjectLevel1
	End
	Behavior = ObjectCreationUpgrade ModuleTag_SpawnObject
		TriggeredBy 	= Upgrade_ObjectLevel1
		ThingToSpawn	= InstantShroudRevealer_09v3
	End

	
	
	GeometryContactPoint = X:20.0	Y:-20.0	Z:0			Repair

	Geometry              = CYLINDER
	GeometryMajorRadius   = 100.0
	GeometryMinorRadius   = 100.0
	GeometryHeight        = 10.0
	GeometryIsSmall       = Yes
	Shadow                = SHADOW_VOLUME
	BuildCompletion     = PLACED_BY_PLAYER
	
End