
		DamageScalar	= 105% NONE +HERO ;;=;;
		DamageScalar	= 55% NONE +STRUCTURE -WargLair -BarrowWightLair -CaveTrollLair -SpiderLair -MoriarGoblinLair -COMMANDCENTER;=;; ;;=CAVETROLLBALANCE=;;
        DamageScalar	= 40% NONE +COMMANDCENTER ;;=CAVETROLLBALANCE=;;
		DamageScalar	= 87% NONE +DwarvenPhalanx  ;;=CAVETROLLBALANCE=;; ; 82% NONE +DwarvenPhalanx  ;;=CAVETROLLBALANCE=;;
		DamageScalar	= 82% NONE +GondorTowerShieldGuard ;;=CAVETROLLBALANCE=;; ; 77% NONE +GondorTowerShieldGuard ;;=CAVETROLLBALANCE=;;
		DamageScalar	= 95% NONE +MordorEasterling ;;=CAVETROLLBALANCE=;; ; 85% NONE +MordorEasterling ;;=CAVETROLLBALANCE=;;
        DamageScalar	= 110% NONE +IsengardPikeman



;;;;;-WildMarauder -GondorTowerShieldGuard -ElvenMithlondSentry -DwarvenPhalanx -IsengardPikeman -MordorEasterling
