		Radius        = 2.5 ;;=;; 4.5 ;;=; 5 ;; 6 ;; 5 ;;=BOMBARDTHINGY=;; 0.0	; HitStoredTarget means we hurt the person we launched at.  And nobody else.  So a miss hurts nobody.
;;;;		DamageTaperOff =11 ;;=;; 8 ;;=;; 12 ;; 10 ;;=BOMBARDTHINGY=;;
;;;;;;;;;;		AcceptDamageAdd = No ;;;;;;;;


;4.5r/11dto was ok till 09/04/15, but taper off causes bombard lose its damage against lairs. Also we better avoid future complains.



;;=;; IF DAMAGE TAPER OFF IS 3.5 OF LOW, THE DAMAGE IS ULTRA LOW.