
		DamageScalar	= 105% NONE +HERO
		DamageScalar	= 50% NONE +STRUCTURE -WargLair -BarrowWightLair -CaveTrollLair -SpiderLair -MoriarGoblinLair -COMMANDCENTER;=;; ;;=CAVETROLLBALANCE=;;
        DamageScalar	= 40% NONE +COMMANDCENTER ;;=CAVETROLLBALANCE=;;
		DamageScalar	= 82% NONE +DwarvenPhalanx  ;;=CAVETROLLBALANCE=;;
		DamageScalar	= 77% NONE +GondorTowerShieldGuard ;;=CAVETROLLBALANCE=;;
		DamageScalar	= 85% NONE +MordorEasterling ;;=CAVETROLLBALANCE=;;




;;;;;-WildMarauder -GondorTowerShieldGuard -ElvenMithlondSentry -DwarvenPhalanx -IsengardPikeman -MordorEasterling
