;;=;;		FIRST THAN ANYTHING; THIS WILL AFFECT ONLY;
;;=;;		Rohan Rohirrim and Goblin Spider Rider.



		DamageScalar  = 115% ALL -WildMarauder -GondorTowerShieldGuard -ElvenMithlondSentry -DwarvenPhalanx -IsengardPikeman -MordorEasterling ;;=FIXING_FIRE_ARROW_SYSTEM=;;



;;=;;		SO, IF SPIDER RIDER BASE DAMAGE IS 41, NOW ITS GONNA BE 47.15, BUT IT WILL NOT BREAK THE COUNTER SYSTEM RAPING PIKES.