;/////////////////////////////////////////////////////////////////////////////
;///	   	Thorins Reach 4Pl by Powerkartoffel                            ///
;///////////////////////////////////////////////////////////////////////////// 

;-----------------------------------------------------------------


ModifierList MineshaftContainedBonus_202aa ;,;
    Category = SPELL
    Modifier = SPEED 375%
  	ModelCondition = USER_70 ;;-;;
 	Modifier = CRUSHABLE_LEVEL 2	//Additive
	Modifier = RESIST_KNOCKBACK 100%
    Duration = 1000
End



AIData
	UseLowLODTrees 		= No ;;.;;
END

WaterTransparency
	ReflectionPlaneZ 	= 3.0;
	ReflectionOn 		= No
End

Weather

	HardwareFogColor 	= R:60 G:50 B:0
	HardwareFogEnable 	= No
	HardwareFogStart 	= 650
	HardwareFogEnd 		= 5000	

End



FXParticleSystem PK_Teleport
  System
    Priority = VERY_LOW_OR_ABOVE
    Shader = ALPHA
    ParticleName = EXsmokeplume.tga

    Lifetime = 90 110
    SortLevel = 1
    Size = 3 6
    BurstDelay = 10 10
    BurstCount = 4 4
  End

  Color = DefaultColor
    Color1 = R:186 G:158 B:141 0
    Color2 = R:120 G:80 B:60 45
  End

  Alpha = DefaultAlpha
    Alpha1 = 0.5 0.6 0
    Alpha2 = 0 0 90
  End

  Update = DefaultUpdate
    SizeRate = 1.5 2.5
    SizeRateDamping = 0.97 0.97
    AngleZ = -0.5 0.5
    AngularRateZ = -0.1 0.1
    AngularDamping = 0.9 0.9
    AngularDampingXY = 1 1
  End

  Physics = DefaultPhysics
    Gravity = 0.015
    VelocityDamping = 0.8 0.85
    DriftVelocity = X:0 Y:0 Z:0
  End

  EmissionVelocity = OutwardEmissionVelocity
  End

  EmissionVolume = CylinderEmissionVolume
    Radius = 40
    Length = 3
  End

  Draw = DefaultDraw
  End
End


ChildObject GenericRockVendorNoStructure GenericRockVendorNoStructure

  ; *** ART Parameters ***
  Draw = W3DScriptedModelDraw ModuleTag_01
	DefaultModelConditionState
		Model = PRDarkGrey01
	End
  End

  ; *** DESIGN parameters ***
  DisplayName      = OBJECT:Prop
  EditorSorting   = MISC_NATURAL
  KindOf = ROCK_VENDOR IMMOBILE IGNORED_IN_GUI INERT INERT_SHROUD_REVEALER CLEARED_BY_BUILD

	TransportSlotCount  = 1  
  ; *** ENGINEERING Parameters ***
  Body = HighlanderBody ModuleTag_02 ;Can take damage, but won't die.  Can only die from ::kill() or other unresistable damage
    MaxHealth      = 1.0
    GrabObject = GenericThrowableRock
    GrabOffset = X:16 Y:0
  End

  ; *** ENGINEERING Parameters ***
;  Shadow              = SHADOW_VOLUME_NON_SELF_2
;  Shadow              = SHADOW_VOLUME
  Shadow              = SHADOW_VOLUME_NEW
  GeometryIsSmall     = Yes
  Geometry            = CYLINDER
  GeometryMajorRadius = 1 ;12
  GeometryHeight      = 1 ;5
  
End

ChildObject DarkRockGrey02 DarkRockGrey02
  KindOf = ROCK_VENDOR IMMOBILE STRUCTURE IGNORED_IN_GUI CAN_SEE_THROUGH_STRUCTURE INERT INERT_SHROUD_REVEALER CAN_CAST_REFLECTIONS
  Shadow              = SHADOW_VOLUME_NEW
  GeometryIsSmall     = Yes
End

ChildObject DarkRockGrey17 DarkRockGrey17
  KindOf = ROCK_VENDOR IMMOBILE STRUCTURE IGNORED_IN_GUI CAN_SEE_THROUGH_STRUCTURE INERT INERT_SHROUD_REVEALER CAN_CAST_REFLECTIONS
  Shadow              = SHADOW_VOLUME_NEW
  GeometryIsSmall     = Yes
End

ChildObject EdorasRock02 EdorasRock02
  KindOf = ROCK_VENDOR IMMOBILE STRUCTURE IGNORED_IN_GUI CAN_SEE_THROUGH_STRUCTURE INERT INERT_SHROUD_REVEALER CAN_CAST_REFLECTIONS
  Shadow              = SHADOW_VOLUME_NEW
  GeometryIsSmall     = Yes
End

ChildObject EdorasRock17 EdorasRock17
  KindOf = ROCK_VENDOR IMMOBILE STRUCTURE IGNORED_IN_GUI CAN_SEE_THROUGH_STRUCTURE INERT INERT_SHROUD_REVEALER CAN_CAST_REFLECTIONS
  Shadow              = SHADOW_VOLUME_NEW
  GeometryIsSmall     = Yes
End

ChildObject IsengardBuildingFoundation IsengardBuildingFoundation

	Draw = W3DScriptedModelDraw ModuleTag_01
		DefaultModelConditionState
			Model = OBBFoundationX
			ParticleSysBone = None PK_Teleport
		End
    End

	Draw = W3DFloorDraw ModuleTag_Draw
		ModelName = HBFoundationX
	End

	SelectPortrait = LWPErebor

	; ***DESIGN parameters ***
	DisplayName        	= OBJECT:WildMineShaft
	Description 	    = OBJECT:UndermineMineShaft
	EditorSorting       = STRUCTURE
	VisionRange         = 160.0          ; Shroud clearing distance
	ShroudClearingRange = GONDOR_WORKSHOP_SHROUD_CLEAR
 	CommandSet			= HobbitWorkPitCommandSet
 
  ArmorSet
    Conditions        = None
    Armor             = InvulnerableArmor ;;=;; StructureArmor ; ;
  End

	; *** AUDIO Parameters ***

	VoiceSelect				= WildDefiledMineSelect

	;UnitSpecificSounds
	;End


	; *** ENGINEERING Parameters ***

	RadarPriority       = STRUCTURE
	KindOf              = PRELOAD STRUCTURE SELECTABLE IMMOBILE SCORE GARRISON GARRISONABLE_UNTIL_DESTROYED MADE_OF_STONE CHUNK_VENDOR ALWAYS_SHOW_HOUSE_COLOR LINKED_TO_FLAG NOT_AUTOACQUIRABLE
	
	Behavior       = EvacuateDamage ModuleTag_evacuateDamage
		DamageToPanicThreshold = 0% 
		TrackingTimeSpan = 100
	End
	Behavior = AttributeModifierAuraUpdate ModuleTag_MineshaftContainedBonus ;;,;;
		StartsActive    = Yes
		BonusName        = MineshaftContainedBonus_202aa
		RefreshDelay    = 100
		AffectContainedOnly = Yes
		AllowSelf = Yes
	End	
	
	Behavior = HordeGarrisonContain ModuleTag_hordeGarrison
		ObjectStatusOfContained	= UNSELECTABLE ENCLOSED 
		ContainMax              = 10
		DamagePercentToUnits    = 0%
		PassengerFilter			= TRANSPORTSHIP_PASSENGER_OBJECTFILTER
		AllowEnemiesInside      = No
		AllowAlliesInside      	= Yes
		AllowNeutralInside      = Yes	; Cause this structure is normally neutral.
;		DoorOpenTime 			= 1
		NumberOfExitPaths       = 1		; Defaults to 1.  Set 0 to not use ExitStart/ExitEnd, set higher than 1 to use ExitStart01-nn/ExitEnd01-nn
		PassengerBonePrefix     = PassengerBone:SAIL_BONE KindOf:INFANTRY
		EntryPosition			= X:3827.0 Y:358.5 Z:0.0
		EntryOffset				= X:0.0 Y:0.0 Z:0.0
		ExitOffset				= X:3763.0 Y:87.5 Z:0.0
		ExitDelay				= 0.1
		EnterSound				= GarrisonEnter
		KillPassengersOnDeath	= No
		ShowPips				= No
	End
	Behavior = GrantUpgradeCreate ModuleTag_GrantUpgrade
		UpgradeToGrant = Upgrade_ObjectLevel1
	End
	Behavior = ObjectCreationUpgrade ModuleTag_SpawnObject
		TriggeredBy 	= Upgrade_ObjectLevel1
		ThingToSpawn	= InstantShroudRevealer_09v3
	End	
	GeometryContactPoint = X:20.0	Y:-20.0	Z:0			Repair

	Geometry              = CYLINDER
	GeometryMajorRadius   = 100.0
	GeometryMinorRadius   = 100.0
	GeometryHeight        = 10.0
	GeometryIsSmall       = Yes
	Shadow                = SHADOW_VOLUME
	BuildCompletion     = PLACED_BY_PLAYER
	
End

ChildObject ElvenBuildingFoundation ElvenBuildingFoundation

	Draw = W3DScriptedModelDraw ModuleTag_01
		DefaultModelConditionState
			Model = OBBFoundationX
			ParticleSysBone = None PK_Teleport
		End
    End

	Draw = W3DFloorDraw ModuleTag_Draw
		ModelName = HBFoundationX
	End
	
	SelectPortrait = LWPErebor

	; ***DESIGN parameters ***
	DisplayName        	= OBJECT:WildMineShaft
	Description 	    = OBJECT:UndermineMineShaft
	EditorSorting       = STRUCTURE
	VisionRange         = 160.0          ; Shroud clearing distance
	ShroudClearingRange = GONDOR_WORKSHOP_SHROUD_CLEAR
 	CommandSet			= HobbitWorkPitCommandSet
 
  ArmorSet
    Conditions        = None
    Armor             = InvulnerableArmor ;;=;; StructureArmor ; ;
  End

	; *** AUDIO Parameters ***

	VoiceSelect				= WildDefiledMineSelect

	;UnitSpecificSounds
	;End


	; *** ENGINEERING Parameters ***

	RadarPriority       = STRUCTURE
	KindOf              = PRELOAD STRUCTURE SELECTABLE IMMOBILE SCORE GARRISON GARRISONABLE_UNTIL_DESTROYED MADE_OF_STONE CHUNK_VENDOR ALWAYS_SHOW_HOUSE_COLOR LINKED_TO_FLAG NOT_AUTOACQUIRABLE
	
	Behavior       = EvacuateDamage ModuleTag_evacuateDamage
		DamageToPanicThreshold = 0% 
		TrackingTimeSpan = 100
	End
	
	
	Behavior = AttributeModifierAuraUpdate ModuleTag_MineshaftContainedBonus ;;,;;
		StartsActive    = Yes
		BonusName        = MineshaftContainedBonus_202aa
		RefreshDelay    = 100
		AffectContainedOnly = Yes
		AllowSelf = Yes
	End	
	
	Behavior = HordeGarrisonContain ModuleTag_hordeGarrison
		ObjectStatusOfContained	= UNSELECTABLE ENCLOSED 
		ContainMax              = 10
		DamagePercentToUnits    = 0%
		PassengerFilter			= TRANSPORTSHIP_PASSENGER_OBJECTFILTER
		AllowEnemiesInside      = No
		AllowAlliesInside      	= Yes
		AllowNeutralInside      = Yes	; Cause this structure is normally neutral.
;		DoorOpenTime 			= 1
		NumberOfExitPaths       = 1		; Defaults to 1.  Set 0 to not use ExitStart/ExitEnd, set higher than 1 to use ExitStart01-nn/ExitEnd01-nn
		PassengerBonePrefix     = PassengerBone:SAIL_BONE KindOf:INFANTRY
		EntryPosition			= X:3915.0 Y:-820.8 Z:0.0
		EntryOffset				= X:0.0 Y:0.0 Z:0.0
		ExitOffset				= X:3774.0 Y:-853.8 Z:0.0
		ExitDelay				= 0.1
		EnterSound				= GarrisonEnter
		KillPassengersOnDeath	= No
		ShowPips				= No
	End
	Behavior = GrantUpgradeCreate ModuleTag_GrantUpgrade
		UpgradeToGrant = Upgrade_ObjectLevel1
	End
	Behavior = ObjectCreationUpgrade ModuleTag_SpawnObject
		TriggeredBy 	= Upgrade_ObjectLevel1
		ThingToSpawn	= InstantShroudRevealer_09v3
	End	
	GeometryContactPoint = X:20.0	Y:-20.0	Z:0			Repair

	Geometry              = CYLINDER
	GeometryMajorRadius   = 100.0
	GeometryMinorRadius   = 100.0
	GeometryHeight        = 10.0
	GeometryIsSmall       = Yes
	Shadow                = SHADOW_VOLUME
	BuildCompletion     = PLACED_BY_PLAYER
	
End

ChildObject GondorBuildingFoundation_Independant GondorBuildingFoundation_Independant

	Draw = W3DScriptedModelDraw ModuleTag_01
		DefaultModelConditionState
			Model = OBBFoundationX
			ParticleSysBone = None PK_Teleport
		End
    End

	Draw = W3DFloorDraw ModuleTag_Draw
		ModelName = HBFoundationX
	End
	
	SelectPortrait = LWPErebor

	; ***DESIGN parameters ***
	DisplayName        	= OBJECT:WildMineShaft
	Description 	    = OBJECT:UndermineMineShaft
	EditorSorting       = STRUCTURE
	VisionRange         = 160.0          ; Shroud clearing distance
	ShroudClearingRange = GONDOR_WORKSHOP_SHROUD_CLEAR
 	CommandSet			= HobbitWorkPitCommandSet
 
  ArmorSet
    Conditions        = None
    Armor             = InvulnerableArmor ;;=;; StructureArmor ; ;
  End

	; *** AUDIO Parameters ***

	VoiceSelect				= WildDefiledMineSelect

	;UnitSpecificSounds
	;End


	; *** ENGINEERING Parameters ***

	RadarPriority       = STRUCTURE
	KindOf              = PRELOAD STRUCTURE SELECTABLE IMMOBILE SCORE GARRISON GARRISONABLE_UNTIL_DESTROYED MADE_OF_STONE CHUNK_VENDOR ALWAYS_SHOW_HOUSE_COLOR LINKED_TO_FLAG NOT_AUTOACQUIRABLE
	
	Behavior       = EvacuateDamage ModuleTag_evacuateDamage
		DamageToPanicThreshold = 0% 
		TrackingTimeSpan = 100
	End
	Behavior = AttributeModifierAuraUpdate ModuleTag_MineshaftContainedBonus ;;,;;
		StartsActive    = Yes
		BonusName        = MineshaftContainedBonus_202aa
		RefreshDelay    = 100
		AffectContainedOnly = Yes
		AllowSelf = Yes
	End	
	
	Behavior = HordeGarrisonContain ModuleTag_hordeGarrison
		ObjectStatusOfContained	= UNSELECTABLE ENCLOSED 
		ContainMax              = 10
		DamagePercentToUnits    = 0%
		PassengerFilter			= TRANSPORTSHIP_PASSENGER_OBJECTFILTER
		AllowEnemiesInside      = No
		AllowAlliesInside      	= Yes
		AllowNeutralInside      = Yes	; Cause this structure is normally neutral.
;		DoorOpenTime 			= 1
		NumberOfExitPaths       = 1		; Defaults to 1.  Set 0 to not use ExitStart/ExitEnd, set higher than 1 to use ExitStart01-nn/ExitEnd01-nn
		PassengerBonePrefix     = PassengerBone:SAIL_BONE KindOf:INFANTRY
		EntryPosition			= X:3915.0 Y:-129.2 Z:0.0
		EntryOffset				= X:0.0 Y:0.0 Z:0.0
		ExitOffset				= X:3690.0 Y:-14.7 Z:0.0
		ExitDelay				= 0.1
		EnterSound				= GarrisonEnter
		KillPassengersOnDeath	= No
		ShowPips				= No
	End
	Behavior = GrantUpgradeCreate ModuleTag_GrantUpgrade
		UpgradeToGrant = Upgrade_ObjectLevel1
	End
	Behavior = ObjectCreationUpgrade ModuleTag_SpawnObject
		TriggeredBy 	= Upgrade_ObjectLevel1
		ThingToSpawn	= InstantShroudRevealer_09v3
	End	
	GeometryContactPoint = X:20.0	Y:-20.0	Z:0			Repair

	Geometry              = CYLINDER
	GeometryMajorRadius   = 100.0
	GeometryMinorRadius   = 100.0
	GeometryHeight        = 10.0
	GeometryIsSmall       = Yes
	Shadow                = SHADOW_VOLUME
	BuildCompletion     = PLACED_BY_PLAYER
	
End


ChildObject GondorBuildingFoundation GondorBuildingFoundation

	Draw = W3DScriptedModelDraw ModuleTag_01
		DefaultModelConditionState
			Model = OBBFoundationX
			ParticleSysBone = None PK_Teleport
		End
    End

	Draw = W3DFloorDraw ModuleTag_Draw
		ModelName = HBFoundationX
	End
	
	SelectPortrait = LWPErebor

	; ***DESIGN parameters ***
	DisplayName        	= OBJECT:WildMineShaft
	Description 	    = OBJECT:UndermineMineShaft
	EditorSorting       = STRUCTURE
	VisionRange         = 160.0          ; Shroud clearing distance
	ShroudClearingRange = GONDOR_WORKSHOP_SHROUD_CLEAR
 	CommandSet			= HobbitWorkPitCommandSet
 
  ArmorSet
    Conditions        = None
    Armor             = InvulnerableArmor ;;=;; StructureArmor ; ;
  End

	; *** AUDIO Parameters ***

	VoiceSelect				= WildDefiledMineSelect

	;UnitSpecificSounds
	;End


	; *** ENGINEERING Parameters ***

	RadarPriority       = STRUCTURE
	KindOf              = PRELOAD STRUCTURE SELECTABLE IMMOBILE SCORE GARRISON GARRISONABLE_UNTIL_DESTROYED MADE_OF_STONE CHUNK_VENDOR ALWAYS_SHOW_HOUSE_COLOR LINKED_TO_FLAG NOT_AUTOACQUIRABLE
	
	Behavior       = EvacuateDamage ModuleTag_evacuateDamage
		DamageToPanicThreshold = 0% 
		TrackingTimeSpan = 100
	End
	Behavior = AttributeModifierAuraUpdate ModuleTag_MineshaftContainedBonus ;;,;;
		StartsActive    = Yes
		BonusName        = MineshaftContainedBonus_202aa
		RefreshDelay    = 100
		AffectContainedOnly = Yes
		AllowSelf = Yes
	End	
	
	Behavior = HordeGarrisonContain ModuleTag_hordeGarrison
		ObjectStatusOfContained	= UNSELECTABLE ENCLOSED 
		ContainMax              = 10
		DamagePercentToUnits    = 0%
		PassengerFilter			= TRANSPORTSHIP_PASSENGER_OBJECTFILTER
		AllowEnemiesInside      = No
		AllowAlliesInside      	= Yes
		AllowNeutralInside      = Yes	; Cause this structure is normally neutral.
;		DoorOpenTime 			= 1
		NumberOfExitPaths       = 1		; Defaults to 1.  Set 0 to not use ExitStart/ExitEnd, set higher than 1 to use ExitStart01-nn/ExitEnd01-nn
		PassengerBonePrefix     = PassengerBone:SAIL_BONE KindOf:INFANTRY
		EntryPosition			= X:3915.0 Y:-803.5 Z:0.0
		EntryOffset				= X:0.0 Y:0.0 Z:0.0
		ExitOffset				= X:3778.0 Y:-812.5 Z:0.0
		ExitDelay				= 0.1
		EnterSound				= GarrisonEnter
		KillPassengersOnDeath	= No
		ShowPips				= No
	End
	
	Behavior = GrantUpgradeCreate ModuleTag_GrantUpgrade
		UpgradeToGrant = Upgrade_ObjectLevel1
	End
	Behavior = ObjectCreationUpgrade ModuleTag_SpawnObject
		TriggeredBy 	= Upgrade_ObjectLevel1
		ThingToSpawn	= InstantShroudRevealer_09v3
	End

	
	
	GeometryContactPoint = X:20.0	Y:-20.0	Z:0			Repair

	Geometry              = CYLINDER
	GeometryMajorRadius   = 100.0
	GeometryMinorRadius   = 100.0
	GeometryHeight        = 10.0
	GeometryIsSmall       = Yes
	Shadow                = SHADOW_VOLUME
	BuildCompletion     = PLACED_BY_PLAYER
	
End

